
dbt_olist:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'vendas_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'vendas_password') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'vendas_db') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
